<?php
namespace Rgriss\Mallard;
use Illuminate\Support\ServiceProvider;

class MallardServiceProvider extends ServiceProvider{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(){
        if ($this->app->runningInConsole()) {
            $this->commands([
                MallardQuackCommand::class,
                MallardInfoCommand::class,
                MallardBackupCommand::class,
            ]);
        }
    }

}